name: Docker Project Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_scan_backend:
    name: Сборка и сканирование backend
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Сборка backend-образа
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: false
          load: true
          tags: docker-project-be:latest

      - name: Запуск Trivy для backend-образа
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker-project-be:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library,os'
          severity: 'HIGH,CRITICAL'

  build_and_scan_frontend:
    name: Сборка и сканирование frontend
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Сборка образа frontend-образа
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: false
          load: true
          tags: docker-project-fe:latest

      - name: Запуск Trivy для frontend-образа
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker-project-fe:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library,os'
          severity: 'HIGH,CRITICAL'

  push_be_to_docker_hub:
    name: Публикация образов в Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_scan_backend]
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Пуш backend-образа в Registry
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-project-be:latest

  push_fe_to_docker_hub:
    name: Публикация образов в Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_scan_frontend]
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Пуш frontend-образа в Registry
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-project-fe:latest

  run_with_docker_compose:
    name: Запуск через Docker Compose
    runs-on: ubuntu-latest
    needs: [push_be_to_docker_hub, push_fe_to_docker_hub]
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Сборка и запуск через Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          up-flags: "--build"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}